

MAP_SIZE = 256, 256
MAP_SCALE = 8

DEFAULT_BLOCK_SIZE = 10, 10
SHIP_SIZE = 10, 10
COLLISION_DETECTION_RADIUS = 2 * DEFAULT_BLOCK_SIZE[0]
# COLLISION_DETECTION_RADIUS = 0

GROUND_LEVEL = 0.7

PLAYER_BASE_HP = 100
PLAYER_BASE_DAMAGE = 25
PLAYER_INCREMENT_DAMAGE = 5
PLAYER_SPEED = MAP_SIZE[0] / 128 / 2

BOT_BASE_HP = 50
BOT_BASE_DAMAGE = 10
BOT_INCREMENT_DAMAGE = 5
ENEMY_SPAWN_INTERVAL = 10
ENEMY_SPEED = PLAYER_SPEED / 2

VISIBLE_SCREEN_MARGIN = DEFAULT_BLOCK_SIZE[:]
VISIBLE_SCREEN_MARGIN = -15, -15
